const TYPE_ACTIONS = {
    CHANGE_ACCEPTANCE: "CHANGE_ACCEPTANCE",
    CHANGE_FIAS_DATA: "CHANGE_FIAS_DATA",
    SET_RESERVATION: "SET_RESERVATION",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    SET_SURNAME: "SET_SURNAME",
    SET_ERROR: "SET_ERROR",
    SET_SERT: "SET_SERT",
    SET_ROOM: "SET_ROOM",
}

export default TYPE_ACTIONS